### ISSUE TITLE
Global Styles overwrite custom paragraph color in toast.

### ISSUE THREAD

**Issue by andrewgremlich** [moharnadreza/react-toast#7]
Hello! I discovered that any global styles using react-toast will overwrite any custom color of the toast paragraph.

The custom color attribute isn't specific or near enough to the element to overwrite the global styles.

I did make a fix and will link the PR...

**Comment by andrewgremlich** [comment]
It seems perhaps I can't link the PR...

**Comment by moharnadreza** [comment]
Hello @andrewgremlich! thanks for the PR ❤️, it's merged and published now and available on [v1.0.2](https://www.npmjs.com/package/react-toast/v/1.0.2).

**Comment by andrewgremlich** [comment]
Thanks for the merge! One more thing though... I don't think the build propagated to NPM, because the built files will still do v1.0.1 stuff.

**Comment by andrewgremlich** [comment]
Looking into the source of the downloaded NPM module, it still does what v1.0.1 did.

**Comment by moharnadreza** [comment]
Aaah yes 😄 did another publish, check [v1.0.3](https://www.npmjs.com/package/react-toast/v/1.0.3) please.

**Comment by andrewgremlich** [comment]
Yup! Fixed and all good!
